### PR TITLE
include/edhoc: add sha_ctx_t type

### PR DESCRIPTION
**Pull request by fjmolinas**
This PR adds a typedef for the `sha_ctx_t` to avoid ifdefs and typecasting.

### CODE REVIEW

**Review by TimothyClaeys — APPROVED** [review]

**Comment by TimothyClaeys** [comment]
I rebased the PR to fix the MBED TLS issue but it seems like there is still a problem.

**Comment by fjmolinas** [comment]
Ah I think I didn't adapt the code for Hacl And Wolfssl, only tinycrypt. I'll take a look on monday!

**Comment by fjmolinas** [comment]
Rebased and pushed, let's see if that was the only issue...

**Comment by fjmolinas** [comment]
@TimothyClaeys all green now!

**Comment by fjmolinas** [comment]
Ping @malishav @TimothyClaeys

**Comment by fjmolinas** [comment]
Ping!

**Comment by malishav** [comment]
I haven't been following this issue, I'll let @TimothyClaeys merge it

**Pull request merged**
